import type { Metadata } from "next";
import { ArrowUpRight, CheckCircle2, CircleDashed, Wrench } from "lucide-react";
import { PageHero } from "@/components/pages/page-hero";
import { SiteShell } from "@/components/site-shell";
import { Badge } from "@/components/ui/badge";
import { projects } from "@/data/site";

export const metadata: Metadata = { title: "Projects" };
export default function ProjectsPage() {
  return <SiteShell><PageHero eyebrow="Projects & initiatives" title="Build work that someone else can continue." description="SESA projects prioritize practical outcomes, readable documentation and clean handover over one-time demonstrations." /><section className="section-pad bg-navy-950 text-ivory"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="grid gap-6 lg:grid-cols-3">{projects.map((project, index) => { const StatusIcon = project.status === "Active" ? Wrench : project.status === "Completed" ? CheckCircle2 : CircleDashed; return <article key={project.id} className="group rounded-[1.8rem] border border-white/10 bg-white/[0.05] p-7 transition hover:-translate-y-1 hover:border-gold/35 hover:bg-white/[0.075]"><div className="flex items-center justify-between gap-4"><Badge className="text-gold-light">{project.category}</Badge><span className="font-display text-4xl text-white/10">0{index + 1}</span></div><h2 className="mt-8 font-display text-4xl leading-tight tracking-[-0.03em]">{project.title}</h2><p className="mt-4 text-sm leading-7 text-slate-300">{project.description}</p><div className="mt-7 flex flex-wrap gap-2">{project.tech.map((item) => <span key={item} className="rounded-full border border-white/10 px-3 py-1 text-xs text-slate-300">{item}</span>)}</div><div className="mt-9 flex items-center justify-between border-t border-white/8 pt-5"><span className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-slate-300"><StatusIcon className="size-4 text-gold-light" />{project.status}</span><ArrowUpRight className="size-5 text-gold-light transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></div></article>; })}</div><div className="mt-10 rounded-[1.75rem] border border-dashed border-white/15 p-8 text-center text-slate-300">Individual project pages, GitHub links, demos and contributor details will be added when real project data is finalized.</div></div></section></SiteShell>;
}
